services:
  web:
    image: node:20-alpine
    container_name: catalyst_web_container
    working_dir: /app
    volumes:
      - ./web:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    networks:
      - catalyst_network

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    image: catalyst_core
    container_name: catalyst_core_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/catalyst
      SPRING_DATASOURCE_USERNAME: catalyst
      SPRING_DATASOURCE_PASSWORD: catalyst
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - catalyst_network

  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalyst
      POSTGRES_USER: catalyst
      POSTGRES_PASSWORD: catalyst
    networks:
      - catalyst_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalyst"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - core
      - web
    networks:
      - catalyst_network

networks:
  catalyst_network:
    driver: bridge
